title: ELITE Metadata Dictionary
projtect_name: ELITE
description: Explore ELITE metadata terms by key, value, or descriptions. 
theme: just-the-docs
logo: "ELITE Logo.png"
url: https://ELITE.github.io/data_models

data_model: EL.data.model.csv

aux_links:
  Data Curator App: https://dca.app.sagebionetworks.org/

callouts:
  highlight:
    color: yellow
  warning:
    title: WARNING
    color: red
  note: 
    color: purple
